GET http://localhost:3000/places?text=av itamar franco, juiz de fora, 3600


###

@originId = ChIJmRM5aqucmAARtxVfylJ8U2o

@destinationId = ChIJ0QAtCg2bmAARcACOYzqfU7U
###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1